inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance

Performance:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  CountAsOne: [ 'array', 'heredoc', 'hash' ]

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'config/environments/**/*'
    - 'config/routes.rb'
    - 'config/routes/**/*'

Metrics/ClassLength:
  Max: 200
